CREATE TABLE public.drains (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    drain_id TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    diameter_cm DOUBLE PRECISION,
    slope DOUBLE PRECISION,
    max_capacity_cm DOUBLE PRECISION NOT NULL,
    expected_flow_lpm DOUBLE PRECISION NOT NULL,
    status TEXT DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.sensor_readings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    drain_id TEXT NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    water_level_cm DOUBLE PRECISION NOT NULL,
    flow_rate_lpm DOUBLE PRECISION NOT NULL,
    rise_rate_cm_min DOUBLE PRECISION NOT NULL,
    sensor_health TEXT DEFAULT 'GOOD',
    battery_voltage DOUBLE PRECISION,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT fk_sensor_drain
        FOREIGN KEY (drain_id)
        REFERENCES public.drains(drain_id)
        ON DELETE CASCADE
);

CREATE TABLE public.weather_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    drain_id TEXT NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    rainfall_mm DOUBLE PRECISION NOT NULL,
    forecast_duration_hours DOUBLE PRECISION NOT NULL,
    rainfall_probability DOUBLE PRECISION,
    rainfall_intensity TEXT,
    weather_condition TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT fk_weather_drain
        FOREIGN KEY (drain_id)
        REFERENCES public.drains(drain_id)
        ON DELETE CASCADE
);

CREATE TABLE public.historical_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    drain_id TEXT NOT NULL,
    event_type TEXT NOT NULL,
    event_date TIMESTAMPTZ NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT fk_history_drain
        FOREIGN KEY (drain_id)
        REFERENCES public.drains(drain_id)
        ON DELETE CASCADE
);

CREATE TABLE public.maintenance_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    drain_id TEXT NOT NULL,
    action TEXT NOT NULL,
    action_date TIMESTAMPTZ NOT NULL,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT fk_maintenance_drain
        FOREIGN KEY (drain_id)
        REFERENCES public.drains(drain_id)
        ON DELETE CASCADE
);

CREATE TABLE public.risk_assessments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    drain_id TEXT NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    wlf DOUBLE PRECISION NOT NULL,
    lrf DOUBLE PRECISION NOT NULL,
    fdf DOUBLE PRECISION NOT NULL,
    frf DOUBLE PRECISION NOT NULL,
    hrf DOUBLE PRECISION NOT NULL,
    blockage_risk DOUBLE PRECISION NOT NULL,
    overflow_risk DOUBLE PRECISION NOT NULL,
    overall_risk DOUBLE PRECISION NOT NULL,
    status TEXT NOT NULL,
    maintenance_priority TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT fk_risk_drain
        FOREIGN KEY (drain_id)
        REFERENCES public.drains(drain_id)
        ON DELETE CASCADE
);

CREATE INDEX idx_sensor_readings_drain_time
ON public.sensor_readings (drain_id, timestamp DESC);

CREATE INDEX idx_weather_data_drain_time
ON public.weather_data (drain_id, timestamp DESC);

CREATE INDEX idx_historical_events_drain_date
ON public.historical_events (drain_id, event_date DESC);

CREATE INDEX idx_maintenance_records_drain_date
ON public.maintenance_records (drain_id, action_date DESC);

CREATE INDEX idx_risk_assessments_drain_time
ON public.risk_assessments (drain_id, timestamp DESC);